### ISSUE TITLE
Test error peek values are "undefined"

### ISSUE THREAD

**Issue by evelant** [MilanKovacic/vitest-visual-studio-code-extension#10]
First off thank you for forking and improving this plugin!

**Describe the bug**
The inline display of a test error value shows the error. The peek popup only shows "undefined" for expected and actual.

**To Reproduce**

`assert.deepEqual(["123"], ["234"])`

**Expected behavior**
Error peek should show the expanded error content, not undefined

**Screenshots**
![image](https://github.com/MilanKovacic/vitest-visual-studio-code-extension/assets/858965/11807c2e-352c-423c-bffa-ffc4e5e7e724)

**Environment**

- OS: macOS
- VSCode version: Cursor Version: 0.24.1
                                VSCode Version: 1.85.1
 
- Vitest version: vitest/1.2.2 darwin-arm64 node-v20.10.0
- Vitest plugin version: 0.3.0

**Additional context**

**Comment by evelant** [comment]
Looked at the dev console and there is an error when showing the error popup

```
workbench.desktop.main.js:21123 Element already has context attribute: test-output-peek-message-container
console.error @ workbench.desktop.main.js:21123
$ @ workbench.desktop.main.js:856
createScoped @ workbench.desktop.main.js:856
R @ workbench.desktop.main.js:989
u @ workbench.desktop.main.js:989
j @ workbench.desktop.main.js:858
createInstance @ workbench.desktop.main.js:858
update @ workbench.desktop.main.js:22230
await in update (async)
(anonymous) @ workbench.desktop.main.js:22230
(anonymous) @ workbench.desktop.main.js:22230
h @ workbench.desktop.main.js:255
(anonymous) @ workbench.desktop.main.js:255
queue @ workbench.desktop.main.js:255
reveal @ workbench.desktop.main.js:22230
showInPlace @ workbench.desktop.main.js:22230
setModel @ workbench.desktop.main.js:22230
show @ workbench.desktop.main.js:22230
C @ workbench.desktop.main.js:22230
await in C (async)
tryPeekFirstError @ workbench.desktop.main.js:22230
F @ workbench.desktop.main.js:22230
y @ workbench.desktop.main.js:201
z @ workbench.desktop.main.js:201
fire @ workbench.desktop.main.js:201
y @ workbench.desktop.main.js:201
z @ workbench.desktop.main.js:201
fire @ workbench.desktop.main.js:201
(anonymous) @ workbench.desktop.main.js:20707
w @ workbench.desktop.main.js:20707
updateState @ workbench.desktop.main.js:20707
(anonymous) @ workbench.desktop.main.js:20991
m @ workbench.desktop.main.js:20991
$updateTestStateInRun @ workbench.desktop.main.js:20991
S @ workbench.desktop.main.js:20998
Q @ workbench.desktop.main.js:20998
M @ workbench.desktop.main.js:20998
L @ workbench.desktop.main.js:20998
(anonymous) @ workbench.desktop.main.js:20998
y @ workbench.desktop.main.js:201
fire @ workbench.desktop.main.js:201
fire @ workbench.desktop.main.js:845
U.onmessage @ workbench.desktop.main.js:21091
```

**Comment by MilanKovacic** [comment]
Hi, I was unable to reproduce this issue on Mac, or Windows.

![image](https://github.com/MilanKovacic/vitest-visual-studio-code-extension/assets/9189985/a7d07a47-a04a-46f6-9b46-819a43366d23)

Could you please post a full test file?

**Comment by evelant** [comment]
Ah it seems it's only an issue when using https://github.com/effect-ts/effect in tests

here's a minimal reproduction https://github.com/evelant/effect-vitest-bug

**Comment by evelant** [comment]
Specifically wrapping a test with this function so that the test can be an `Effect` seems to cause the problem

```ts

export const effect = (() => {
    const f = <E, A>(
        name: string,
        self: () => Effect.Effect<TestServices.TestServices, E, A>,
        timeout: number | V.TestOptions = 5_000,
    ) => {
        return it(name, () => pipe(Effect.suspend(self), Effect.provide(TestEnv), Effect.runPromise), timeout)
    }
    return Object.assign(f, {
        skip: <E, A>(name: string, self: () => Effect.Effect<TestServices.TestServices, E, A>, timeout = 5_000) => {
            return it.skip(name, () => pipe(Effect.suspend(self), Effect.provide(TestEnv), Effect.runPromise), timeout)
        },
        only: <E, A>(name: string, self: () => Effect.Effect<TestServices.TestServices, E, A>, timeout = 5_000) => {
            return it.only(name, () => pipe(Effect.suspend(self), Effect.provide(TestEnv), Effect.runPromise), timeout)
        },
    })
})()
```

I'm not sure why this would cause a problem, it's just returning a test that returns a promise as normal

**Comment by evelant** [comment]
A more minimal reproduction case

```ts
  it(`test2`, async () => {
    await pipe(
      Effect.gen(function* (_) {
        assert.deepEqual(["123"], ["234"]);
      }),
      Effect.runPromise
    );
  })
```

results in an error in the extension

```

workbench.desktop.main.js:21123 [Extension Host] TypeError: Cannot read properties of undefined (reading 'item')
	at a (/Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:2916)
	at a (/Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:3398)
	at qk (/Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:2777)
	at Wa (/Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:2727)
	at uh (/Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:8144)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:4298
	at async Promise.allSettled (index 0)
	at async Rx (/Users/imagio/.cursor/extensions/milan-kovacic.vitest-lab-0.3.0/dist/extension.js:41:4092)
	at async s.u (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:146:6591)
	at async Promise.all (index 0)
```

**Comment by evelant** [comment]
Looks like `data` is undefined somehow at https://github.com/MilanKovacic/vitest-visual-studio-code-extension/blob/a335c3d7a89941155a5ef70c484417824216ef5d/src/watch.ts#L388-L399

**Comment by MilanKovacic** [comment]
Current test parser is very rudimentary, and does not support dynamic tests well.
In the future, I plan to expand it, but currently I am vary of modifying it too much until basics are implemented (tests, CI/CD, etc).

What is the reason you use such wrapper for tests?

**Comment by evelant** [comment]
A lot of my code uses `Effect` so I need to use it a lot in tests. The wrapper makes that less verbose.

It fails even without a wrapper however, just awaiting a promise with no wrapper utility

```ts
  it(`test2`, async () => {
    await pipe(
      Effect.gen(function* (_) {
        assert.deepEqual(["123"], ["234"]);
      }),
      Effect.runPromise
    );
  })
```

**Comment by evelant** [comment]
I ran the above test case with the debugger attached and I couldn't figure out why it fails to show any output. The test case is picked up and run, the TestResult output appears correct, and the text output from vitest appears correct, but for some reason the failure isn't shown in the test results panel or inline in the test file. Only the fail result is indicated in the extension panel, the failure output gets lost somewhere.

**Comment by evelant** [comment]
By the way the launch configurations are incorrect and need to be modified before the debugger will work. `outFiles` needs to be changed to

```
"outFiles": [
        "${workspaceRoot}/dist/**/*.js"
      ],
```

**Comment by evelant** [comment]
OK after a little more debugging it seems like this might be a problem in vitest. Results are returned correctly but for some reason when using `Effect` the `expected` and `actual` fields of the error in the result object for the test are undefined even though the `message` field correct says `'expected [ '123' ] to deeply equal [ '234' ]'`

**Comment by evelant** [comment]
Filed issue with vitest here https://github.com/vitest-dev/vitest/issues/5109

**Comment by evelant** [comment]
OK turns out it's an issue with how Effect handles errors, nothing wrong with this plugin or with vitest! Sorry for the noise.

**Comment by MilanKovacic** [comment]
Hi, no problem. If it still dosn't work correctly after adapting the effect, feel free to reopen the issue.
